Add missing library dependency.
libnativehelper/include/nativehelper/JNIHelp.h:144: error: undefined reference to 'jniThrowNullPointerException'
libnativehelper/include/nativehelper/JNIHelp.h:144: error: undefined reference to 'jniThrowNullPointerException'
libnativehelper/include/nativehelper/ScopedBytes.h:36: error: undefined reference to 'JniConstants::byteArrayClass'
libnativehelper/include/nativehelper/JNIHelp.h:144: error: undefined reference to 'jniThrowNullPointerException'
libnativehelper/include/nativehelper/JNIHelp.h:144: error: undefined reference to 'jniThrowNullPointerException'

All 5 references above are actually in dead code, and -Wl,-gc-sections normally throws them out.
But not with ASan:
https://code.google.com/p/address-sanitizer/issues/detail?id=260

Bug: 21785137
Change-Id: Ic272384cc1a6f77e81079bf4f4ea751a0ed92ea1